
postgresDriverClass=org.postgresql.Driver
postgresUrl=jdbc:postgresql://localhost:5432/MOMEDARA
postgresUserName=postgres
postgresPassword=postgres

mysqlDriverClass=com.mysql.jdbc.Driver
mysqlUrl=jdbc:mysql://localhost:3306/emp?createDatabaseIfNotExist=true
mysqlUserName=root
mysqlPassword=root