url=https://test.salesforce.com
oppUrl=https://ciscosales--mon.lightning.force.com/lightning/r/Opportunity/0063400001DSkxDAAT/view
userName=ngfcsftuser.gen@stage.cisco.com.mon
password=Csngfr3@2019 
servicesInitialPassError=Test pass: Errors are displayed for Services
servicesInitialFailError=Test fail: Errors are NOT displayed for Services
oppName=BMX Series 25
accName=BRADESCO
bookDate=9/12/2020
expProd=280
expServ=350
dealId=19339613
existingOppName=Test CAD for INR